TARGET  = pfftr

PASMO	= pasmo6
PASMOFLAGS = --tapbas --listing gorgon.lst
ZX7 = zx7/zx7

EMU	= fuse
#EMUFLAGS= --late-timings --graphics-filter advmame2x --no-confirm-action
EMUFLAGS= --late-timings --graphics-filter 2x --no-confirm-action

INCLUDES = \
	macros.asm \
	key.asm \
	fatfont.inc \
	playerdata.inc \
	ytable.asm \
	colors.inc 

.PHONY : all run assets clean fullclean

all : clean $(ZX7) $(TARGET).tap run

$(TARGET).tap : $(TARGET).asm $(INCLUDES)
	@echo "[assembling to .tap"]
	@$(PASMO) $(PASMOFLAGS) $< $@

run :
	@$(EMU) $(EMUFLAGS) $(TARGET).tap 2> /dev/null

colors.inc :
	@echo "[creating colors]"
	@makers/createColorNames.sh > $@

fatfont.inc : assets/fatfont.txt
	@echo "[creating fatfont]"
	@echo ";" > $@
	@echo "; Autogenerated by createFont.sh" >> $@
	@echo ";" >> $@
	@echo "FatFont:" >> $@
	@makers/createFont.sh $< 32 >>$@

playerdata.inc: assets/player.txt  
	@echo "[spriting ships]"
	@echo ";" > $@
	@echo "; Autogenerated by spriter.sh" >> $@
	@echo ";" >> $@
	@makers/spriter.sh $< player >> $@

$(ZX7) :
	@$(MAKE) --no-print-directory -C zx7 all

-include Makefile.tmp

Makefile.tmp: Makefile
	@touch $@
	@$(MAKE) -s fullclean


fullclean : clean
	@rm -f *.inc
	@$(MAKE) --no-print-directory -C zx7 clean

clean :
	@rm -rf *.tap *.bin *.lst
	@rm -f *~ */*~
